---
nginx_container_state: present
nginx_container_name: custom_nginx
nginx_image: nginx:latest
nginx_http_host_port: 8080
nginx_https_host_port: 443
nginx_custom_message: "Hello from Ansible-managed Nginx!"
nginx_domen:  myk8s-qqq.webhop.me
